# Generated by Django 4.2.7 on 2023-11-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estimated_time', models.PositiveIntegerField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
