# Generated by Django 4.2.7 on 2023-11-01 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cab_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('booking_time', models.DateTimeField()),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cab_app.cab')),
            ],
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
