# Generated by Django 4.2.7 on 2023-11-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cab_app', '0002_cabbooking_delete_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cab',
            name='driver_name',
        ),
    ]
