# Generated by Django 4.2.7 on 2023-11-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cab_app', '0003_remove_cab_driver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabbooking',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='cabbooking',
            name='cab',
        ),
    ]
