# Generated by Django 4.2.7 on 2023-11-02 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cab_app', '0004_remove_cabbooking_booking_time_remove_cabbooking_cab'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city1', models.CharField(max_length=50)),
                ('city2', models.CharField(max_length=50)),
                ('time', models.IntegerField(default=100000)),
            ],
        ),
        migrations.AddField(
            model_name='cab',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='booking_start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 13, 55, 46, 215949)),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='cab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cab_app.cab'),
        ),
    ]
