# Generated by Django 4.2.7 on 2023-11-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cab_app', '0005_routemap_cab_price_cabbooking_booking_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabbooking',
            name='booking_start_time',
        ),
        migrations.RemoveField(
            model_name='cabbooking',
            name='cab',
        ),
    ]
