# Generated by Django 4.2.7 on 2023-11-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_app', '0006_remove_cabbooking_booking_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='time',
            field=models.BigIntegerField(default=0),
        ),
    ]
