# Generated by Django 4.2.7 on 2023-11-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cab_app', '0007_cabbooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabbooking',
            name='time',
        ),
    ]
