# Generated by Django 4.2.7 on 2023-11-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_app', '0008_remove_cabbooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
